spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
security-frame:
  jwt-config: #配置jwt相关设置
      access-token-expire: 600000 #accessToken的存活时间
      refresh-token-expire: 3000000 #refreshToken的存活时间
      secret: fhsuhfuhfuf #jwt加密的密钥
      access-token-name: access-token1 #设置accessToken的名字
      refresh-token-name: refresh-token1 #设置jwtToken的名字
  result-entity: #返回的实体的配置
    path: com.ppc.common.result.R #指定返回通用实体类的地址
    code-field-name: code #这三个配置是返回实体类的字段名字
    message-field-name: message
    data-field-name: data
  authentication-config:
    release-path:
      - /login
      - swagger
      - api-docs
      - .ico #无需认证的url
    username-field-name: username #前端传入的json中username的字段名
    code-field-name-success-code: 1000 #用户返回实体的code，表示认证成功时的码值
logging:
  level:
    root: debug


